#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pairs' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER k
#  2. INTEGER_ARRAY arr
#

def pairs(k, arr):
    arr.sort()
    i = 0
    j = 1
    count = 0
    while j < len(arr):
        if i == j:
            j += 1
            continue
        temp = arr[j]-arr[i]
        if temp < k:
            j +=1
        elif temp > k:
            i += 1
        else:
            count += 1
            i+= 1
        
    return count

   
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    result = pairs(k, arr)

    fptr.write(str(result) + '\n')

    fptr.close()
