#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'palindromeIndex' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def palindromeIndex(s):
    i = 0
    j = len(s)-1
    if s == s[::-1]:
        return -1
    while i !=j:
        if s[i] == s[j]:
            i +=1
            j -= 1
        else:
            dup1 = s[:i]+s[i+1:]
            dup2 = s[:j]+s[j+1:]
            if dup1 == dup1[::-1]:
                return i
            elif dup2 == dup2[::-1]:
                return j
    return -1
                    
                
        
            
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = palindromeIndex(s)

        fptr.write(str(result) + '\n')

    fptr.close()
